// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/protocol/mitre/stix/v2/stix.proto

/*
Package stixv2 is a generated protocol buffer package.

It is generated from these files:
	pkg/protocol/mitre/stix/v2/stix.proto

It has these top-level messages:
	ExternalReference
	KillChainPhase
	MarkingDefinition
	ObservableObject
	AttackPattern
	Campaign
	CourseOfAction
	Identity
	Indicator
	IntrusionSet
	Malware
	ObservedData
	Report
	ThreatActor
	Tool
	Vulnerability
	RelationShip
	Sighting
*/
package stixv2

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// External references is used to link to external resource.
type ExternalReference struct {
	SourceName string `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	ExternalId string `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Url        string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
}

func (m *ExternalReference) Reset()                    { *m = ExternalReference{} }
func (m *ExternalReference) String() string            { return proto.CompactTextString(m) }
func (*ExternalReference) ProtoMessage()               {}
func (*ExternalReference) Descriptor() ([]byte, []int) { return fileDescriptorStix, []int{0} }

func (m *ExternalReference) GetSourceName() string {
	if m != nil {
		return m.SourceName
	}
	return ""
}

func (m *ExternalReference) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *ExternalReference) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// KillChainPhase describes which pahse of the kill chain the resource in acting.
type KillChainPhase struct {
	PhaseName     string `protobuf:"bytes,1,opt,name=phase_name,json=phaseName,proto3" json:"phase_name,omitempty"`
	KillChainName string `protobuf:"bytes,2,opt,name=kill_chain_name,json=killChainName,proto3" json:"kill_chain_name,omitempty"`
}

func (m *KillChainPhase) Reset()                    { *m = KillChainPhase{} }
func (m *KillChainPhase) String() string            { return proto.CompactTextString(m) }
func (*KillChainPhase) ProtoMessage()               {}
func (*KillChainPhase) Descriptor() ([]byte, []int) { return fileDescriptorStix, []int{1} }

func (m *KillChainPhase) GetPhaseName() string {
	if m != nil {
		return m.PhaseName
	}
	return ""
}

func (m *KillChainPhase) GetKillChainName() string {
	if m != nil {
		return m.KillChainName
	}
	return ""
}

// MarkingDefinition ... .
type MarkingDefinition struct {
	Type           string            `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id             string            `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedByRef   string            `protobuf:"bytes,3,opt,name=created_by_ref,json=createdByRef,proto3" json:"created_by_ref,omitempty"`
	Created        string            `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Modified       string            `protobuf:"bytes,5,opt,name=modified,proto3" json:"modified,omitempty"`
	DefinitionType string            `protobuf:"bytes,9,opt,name=definition_type,json=definitionType,proto3" json:"definition_type,omitempty"`
	Definitions    map[string]string `protobuf:"bytes,10,rep,name=definitions" json:"definitions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *MarkingDefinition) Reset()                    { *m = MarkingDefinition{} }
func (m *MarkingDefinition) String() string            { return proto.CompactTextString(m) }
func (*MarkingDefinition) ProtoMessage()               {}
func (*MarkingDefinition) Descriptor() ([]byte, []int) { return fileDescriptorStix, []int{2} }

func (m *MarkingDefinition) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MarkingDefinition) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MarkingDefinition) GetCreatedByRef() string {
	if m != nil {
		return m.CreatedByRef
	}
	return ""
}

func (m *MarkingDefinition) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *MarkingDefinition) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

func (m *MarkingDefinition) GetDefinitionType() string {
	if m != nil {
		return m.DefinitionType
	}
	return ""
}

func (m *MarkingDefinition) GetDefinitions() map[string]string {
	if m != nil {
		return m.Definitions
	}
	return nil
}

// ObservableObject ... .
type ObservableObject struct {
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (m *ObservableObject) Reset()                    { *m = ObservableObject{} }
func (m *ObservableObject) String() string            { return proto.CompactTextString(m) }
func (*ObservableObject) ProtoMessage()               {}
func (*ObservableObject) Descriptor() ([]byte, []int) { return fileDescriptorStix, []int{3} }

func (m *ObservableObject) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// A type of Tactics, Techniques, and Procedures (TTP) that describes
// ways threat actors attempt to compromise targets.
type AttackPattern struct {
	Type                       string               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                         string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedByRef               string               `protobuf:"bytes,3,opt,name=created_by_ref,json=createdByRef,proto3" json:"created_by_ref,omitempty"`
	Created                    string               `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Modified                   string               `protobuf:"bytes,5,opt,name=modified,proto3" json:"modified,omitempty"`
	Revoked                    bool                 `protobuf:"varint,6,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Labels                     []string             `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty"`
	ExternalReferences         []*ExternalReference `protobuf:"bytes,8,rep,name=external_references,json=externalReferences" json:"external_references,omitempty"`
	ObjectMarkingRefs          []string             `protobuf:"bytes,9,rep,name=object_marking_refs,json=objectMarkingRefs" json:"object_marking_refs,omitempty"`
	GranularMarkings           []string             `protobuf:"bytes,10,rep,name=granular_markings,json=granularMarkings" json:"granular_markings,omitempty"`
	Name                       string               `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	Description                string               `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	KillChainPhases            []*KillChainPhase    `protobuf:"bytes,13,rep,name=kill_chain_phases,json=killChainPhases" json:"kill_chain_phases,omitempty"`
	XMitreVersion              string               `protobuf:"bytes,14,opt,name=x_mitre_version,json=xMitreVersion,proto3" json:"x_mitre_version,omitempty"`
	XMitrePermissionsRequired  []string             `protobuf:"bytes,15,rep,name=x_mitre_permissions_required,json=xMitrePermissionsRequired" json:"x_mitre_permissions_required,omitempty"`
	XMitrePlatforms            []string             `protobuf:"bytes,16,rep,name=x_mitre_platforms,json=xMitrePlatforms" json:"x_mitre_platforms,omitempty"`
	XMitreDetection            string               `protobuf:"bytes,17,opt,name=x_mitre_detection,json=xMitreDetection,proto3" json:"x_mitre_detection,omitempty"`
	XMitreContributors         []string             `protobuf:"bytes,18,rep,name=x_mitre_contributors,json=xMitreContributors" json:"x_mitre_contributors,omitempty"`
	XMitreDataSources          []string             `protobuf:"bytes,19,rep,name=x_mitre_data_sources,json=xMitreDataSources" json:"x_mitre_data_sources,omitempty"`
	XMitreEffectivePermissions []string             `protobuf:"bytes,20,rep,name=x_mitre_effective_permissions,json=xMitreEffectivePermissions" json:"x_mitre_effective_permissions,omitempty"`
	XMitreSystemRequirements   []string             `protobuf:"bytes,21,rep,name=x_mitre_system_requirements,json=xMitreSystemRequirements" json:"x_mitre_system_requirements,omitempty"`
}

func (m *AttackPattern) Reset()                    { *m = AttackPattern{} }
func (m *AttackPattern) String() string            { return proto.CompactTextString(m) }
func (*AttackPattern) ProtoMessage()               {}
func (*AttackPattern) Descriptor() ([]byte, []int) { return fileDescriptorStix, []int{4} }

func (m *AttackPattern) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AttackPattern) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AttackPattern) GetCreatedByRef() string {
	if m != nil {
		return m.CreatedByRef
	}
	return ""
}

func (m *AttackPattern) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *AttackPattern) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

func (m *AttackPattern) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *AttackPattern) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *AttackPattern) GetExternalReferences() []*ExternalReference {
	if m != nil {
		return m.ExternalReferences
	}
	return nil
}

func (m *AttackPattern) GetObjectMarkingRefs() []string {
	if m != nil {
		return m.ObjectMarkingRefs
	}
	return nil
}

func (m *AttackPattern) GetGranularMarkings() []string {
	if m != nil {
		return m.GranularMarkings
	}
	return nil
}

func (m *AttackPattern) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AttackPattern) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AttackPattern) GetKillChainPhases() []*KillChainPhase {
	if m != nil {
		return m.KillChainPhases
	}
	return nil
}

func (m *AttackPattern) GetXMitreVersion() string {
	if m != nil {
		return m.XMitreVersion
	}
	return ""
}

func (m *AttackPattern) GetXMitrePermissionsRequired() []string {
	if m != nil {
		return m.XMitrePermissionsRequired
	}
	return nil
}

func (m *AttackPattern) GetXMitrePlatforms() []string {
	if m != nil {
		return m.XMitrePlatforms
	}
	return nil
}

func (m *AttackPattern) GetXMitreDetection() string {
	if m != nil {
		return m.XMitreDetection
	}
	return ""
}

func (m *AttackPattern) GetXMitreContributors() []string {
	if m != nil {
		return m.XMitreContributors
	}
	return nil
}

func (m *AttackPattern) GetXMitreDataSources() []string {
	if m != nil {
		return m.XMitreDataSources
	}
	return nil
}

func (m *AttackPattern) GetXMitreEffectivePermissions() []string {
	if m != nil {
		return m.XMitreEffectivePermissions
	}
	return nil
}

func (m *AttackPattern) GetXMitreSystemRequirements() []string {
	if m != nil {
		return m.XMitreSystemRequirements
	}
	return nil
}

// A grouping of adversarial behaviors that describes a set of
// malicious activities or attacks that occur over a period of time
// against a specific set of targets.
type Campaign struct {
	Type               string               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                 string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedByRef       string               `protobuf:"bytes,3,opt,name=created_by_ref,json=createdByRef,proto3" json:"created_by_ref,omitempty"`
	Created            string               `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Modified           string               `protobuf:"bytes,5,opt,name=modified,proto3" json:"modified,omitempty"`
	Revoked            bool                 `protobuf:"varint,6,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Labels             []string             `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty"`
	ExternalReferences []*ExternalReference `protobuf:"bytes,8,rep,name=external_references,json=externalReferences" json:"external_references,omitempty"`
	ObjectMarkingRefs  []string             `protobuf:"bytes,9,rep,name=object_marking_refs,json=objectMarkingRefs" json:"object_marking_refs,omitempty"`
	GranularMarkings   []string             `protobuf:"bytes,10,rep,name=granular_markings,json=granularMarkings" json:"granular_markings,omitempty"`
	Name               string               `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	Description        string               `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	Aliases            []string             `protobuf:"bytes,13,rep,name=aliases" json:"aliases,omitempty"`
	FirstSeen          string               `protobuf:"bytes,14,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen           string               `protobuf:"bytes,15,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Objective          string               `protobuf:"bytes,16,opt,name=objective,proto3" json:"objective,omitempty"`
}

func (m *Campaign) Reset()                    { *m = Campaign{} }
func (m *Campaign) String() string            { return proto.CompactTextString(m) }
func (*Campaign) ProtoMessage()               {}
func (*Campaign) Descriptor() ([]byte, []int) { return fileDescriptorStix, []int{5} }

func (m *Campaign) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Campaign) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Campaign) GetCreatedByRef() string {
	if m != nil {
		return m.CreatedByRef
	}
	return ""
}

func (m *Campaign) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Campaign) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

func (m *Campaign) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *Campaign) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Campaign) GetExternalReferences() []*ExternalReference {
	if m != nil {
		return m.ExternalReferences
	}
	return nil
}

func (m *Campaign) GetObjectMarkingRefs() []string {
	if m != nil {
		return m.ObjectMarkingRefs
	}
	return nil
}

func (m *Campaign) GetGranularMarkings() []string {
	if m != nil {
		return m.GranularMarkings
	}
	return nil
}

func (m *Campaign) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Campaign) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Campaign) GetAliases() []string {
	if m != nil {
		return m.Aliases
	}
	return nil
}

func (m *Campaign) GetFirstSeen() string {
	if m != nil {
		return m.FirstSeen
	}
	return ""
}

func (m *Campaign) GetLastSeen() string {
	if m != nil {
		return m.LastSeen
	}
	return ""
}

func (m *Campaign) GetObjective() string {
	if m != nil {
		return m.Objective
	}
	return ""
}

// An action taken to either prevent an attack or respond to an attack.
type CourseOfAction struct {
	Type               string               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                 string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedByRef       string               `protobuf:"bytes,3,opt,name=created_by_ref,json=createdByRef,proto3" json:"created_by_ref,omitempty"`
	Created            string               `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Modified           string               `protobuf:"bytes,5,opt,name=modified,proto3" json:"modified,omitempty"`
	Revoked            bool                 `protobuf:"varint,6,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Labels             []string             `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty"`
	ExternalReferences []*ExternalReference `protobuf:"bytes,8,rep,name=external_references,json=externalReferences" json:"external_references,omitempty"`
	ObjectMarkingRefs  []string             `protobuf:"bytes,9,rep,name=object_marking_refs,json=objectMarkingRefs" json:"object_marking_refs,omitempty"`
	GranularMarkings   []string             `protobuf:"bytes,10,rep,name=granular_markings,json=granularMarkings" json:"granular_markings,omitempty"`
	Name               string               `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	Description        string               `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *CourseOfAction) Reset()                    { *m = CourseOfAction{} }
func (m *CourseOfAction) String() string            { return proto.CompactTextString(m) }
func (*CourseOfAction) ProtoMessage()               {}
func (*CourseOfAction) Descriptor() ([]byte, []int) { return fileDescriptorStix, []int{6} }

func (m *CourseOfAction) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CourseOfAction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CourseOfAction) GetCreatedByRef() string {
	if m != nil {
		return m.CreatedByRef
	}
	return ""
}

func (m *CourseOfAction) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *CourseOfAction) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

func (m *CourseOfAction) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *CourseOfAction) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *CourseOfAction) GetExternalReferences() []*ExternalReference {
	if m != nil {
		return m.ExternalReferences
	}
	return nil
}

func (m *CourseOfAction) GetObjectMarkingRefs() []string {
	if m != nil {
		return m.ObjectMarkingRefs
	}
	return nil
}

func (m *CourseOfAction) GetGranularMarkings() []string {
	if m != nil {
		return m.GranularMarkings
	}
	return nil
}

func (m *CourseOfAction) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CourseOfAction) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// Individuals, organizations, or groups, as well as classes of
// individuals, organizations, or groups.
type Identity struct {
	Type               string               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                 string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedByRef       string               `protobuf:"bytes,3,opt,name=created_by_ref,json=createdByRef,proto3" json:"created_by_ref,omitempty"`
	Created            string               `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Modified           string               `protobuf:"bytes,5,opt,name=modified,proto3" json:"modified,omitempty"`
	Revoked            bool                 `protobuf:"varint,6,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Labels             []string             `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty"`
	ExternalReferences []*ExternalReference `protobuf:"bytes,8,rep,name=external_references,json=externalReferences" json:"external_references,omitempty"`
	ObjectMarkingRefs  []string             `protobuf:"bytes,9,rep,name=object_marking_refs,json=objectMarkingRefs" json:"object_marking_refs,omitempty"`
	GranularMarkings   []string             `protobuf:"bytes,10,rep,name=granular_markings,json=granularMarkings" json:"granular_markings,omitempty"`
	Name               string               `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	Description        string               `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	IdentityClass      string               `protobuf:"bytes,13,opt,name=identity_class,json=identityClass,proto3" json:"identity_class,omitempty"`
	Sectors            []string             `protobuf:"bytes,14,rep,name=sectors" json:"sectors,omitempty"`
	ContactInformation string               `protobuf:"bytes,15,opt,name=contact_information,json=contactInformation,proto3" json:"contact_information,omitempty"`
}

func (m *Identity) Reset()                    { *m = Identity{} }
func (m *Identity) String() string            { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()               {}
func (*Identity) Descriptor() ([]byte, []int) { return fileDescriptorStix, []int{7} }

func (m *Identity) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Identity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Identity) GetCreatedByRef() string {
	if m != nil {
		return m.CreatedByRef
	}
	return ""
}

func (m *Identity) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Identity) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

func (m *Identity) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *Identity) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Identity) GetExternalReferences() []*ExternalReference {
	if m != nil {
		return m.ExternalReferences
	}
	return nil
}

func (m *Identity) GetObjectMarkingRefs() []string {
	if m != nil {
		return m.ObjectMarkingRefs
	}
	return nil
}

func (m *Identity) GetGranularMarkings() []string {
	if m != nil {
		return m.GranularMarkings
	}
	return nil
}

func (m *Identity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Identity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Identity) GetIdentityClass() string {
	if m != nil {
		return m.IdentityClass
	}
	return ""
}

func (m *Identity) GetSectors() []string {
	if m != nil {
		return m.Sectors
	}
	return nil
}

func (m *Identity) GetContactInformation() string {
	if m != nil {
		return m.ContactInformation
	}
	return ""
}

// Contains a pattern that can be used to detect suspicious or
// malicious cyber activity.
type Indicator struct {
	Type               string               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                 string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedByRef       string               `protobuf:"bytes,3,opt,name=created_by_ref,json=createdByRef,proto3" json:"created_by_ref,omitempty"`
	Created            string               `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Modified           string               `protobuf:"bytes,5,opt,name=modified,proto3" json:"modified,omitempty"`
	Revoked            bool                 `protobuf:"varint,6,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Labels             []string             `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty"`
	ExternalReferences []*ExternalReference `protobuf:"bytes,8,rep,name=external_references,json=externalReferences" json:"external_references,omitempty"`
	ObjectMarkingRefs  []string             `protobuf:"bytes,9,rep,name=object_marking_refs,json=objectMarkingRefs" json:"object_marking_refs,omitempty"`
	GranularMarkings   []string             `protobuf:"bytes,10,rep,name=granular_markings,json=granularMarkings" json:"granular_markings,omitempty"`
	Name               string               `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	Description        string               `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	Pattern            string               `protobuf:"bytes,13,opt,name=pattern,proto3" json:"pattern,omitempty"`
	ValidFrom          string               `protobuf:"bytes,14,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidUntil         string               `protobuf:"bytes,15,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	KillChainPhases    []*KillChainPhase    `protobuf:"bytes,16,rep,name=kill_chain_phases,json=killChainPhases" json:"kill_chain_phases,omitempty"`
}

func (m *Indicator) Reset()                    { *m = Indicator{} }
func (m *Indicator) String() string            { return proto.CompactTextString(m) }
func (*Indicator) ProtoMessage()               {}
func (*Indicator) Descriptor() ([]byte, []int) { return fileDescriptorStix, []int{8} }

func (m *Indicator) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Indicator) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Indicator) GetCreatedByRef() string {
	if m != nil {
		return m.CreatedByRef
	}
	return ""
}

func (m *Indicator) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Indicator) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

func (m *Indicator) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *Indicator) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Indicator) GetExternalReferences() []*ExternalReference {
	if m != nil {
		return m.ExternalReferences
	}
	return nil
}

func (m *Indicator) GetObjectMarkingRefs() []string {
	if m != nil {
		return m.ObjectMarkingRefs
	}
	return nil
}

func (m *Indicator) GetGranularMarkings() []string {
	if m != nil {
		return m.GranularMarkings
	}
	return nil
}

func (m *Indicator) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Indicator) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Indicator) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *Indicator) GetValidFrom() string {
	if m != nil {
		return m.ValidFrom
	}
	return ""
}

func (m *Indicator) GetValidUntil() string {
	if m != nil {
		return m.ValidUntil
	}
	return ""
}

func (m *Indicator) GetKillChainPhases() []*KillChainPhase {
	if m != nil {
		return m.KillChainPhases
	}
	return nil
}

// A grouped set of adversarial behaviors and resources with common
// properties believed to be orchestrated by a single threat actor.
type IntrusionSet struct {
	Type                 string               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedByRef         string               `protobuf:"bytes,3,opt,name=created_by_ref,json=createdByRef,proto3" json:"created_by_ref,omitempty"`
	Created              string               `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Modified             string               `protobuf:"bytes,5,opt,name=modified,proto3" json:"modified,omitempty"`
	Revoked              bool                 `protobuf:"varint,6,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Labels               []string             `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty"`
	ExternalReferences   []*ExternalReference `protobuf:"bytes,8,rep,name=external_references,json=externalReferences" json:"external_references,omitempty"`
	ObjectMarkingRefs    []string             `protobuf:"bytes,9,rep,name=object_marking_refs,json=objectMarkingRefs" json:"object_marking_refs,omitempty"`
	GranularMarkings     []string             `protobuf:"bytes,10,rep,name=granular_markings,json=granularMarkings" json:"granular_markings,omitempty"`
	Name                 string               `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	Description          string               `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	Aliases              []string             `protobuf:"bytes,13,rep,name=aliases" json:"aliases,omitempty"`
	FirstSeen            string               `protobuf:"bytes,14,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen             string               `protobuf:"bytes,15,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Goals                []string             `protobuf:"bytes,16,rep,name=goals" json:"goals,omitempty"`
	ResourceLevel        string               `protobuf:"bytes,17,opt,name=resource_level,json=resourceLevel,proto3" json:"resource_level,omitempty"`
	PrimaryMotivation    string               `protobuf:"bytes,18,opt,name=primary_motivation,json=primaryMotivation,proto3" json:"primary_motivation,omitempty"`
	SecondaryMotivations []string             `protobuf:"bytes,19,rep,name=secondary_motivations,json=secondaryMotivations" json:"secondary_motivations,omitempty"`
}

func (m *IntrusionSet) Reset()                    { *m = IntrusionSet{} }
func (m *IntrusionSet) String() string            { return proto.CompactTextString(m) }
func (*IntrusionSet) ProtoMessage()               {}
func (*IntrusionSet) Descriptor() ([]byte, []int) { return fileDescriptorStix, []int{9} }

func (m *IntrusionSet) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *IntrusionSet) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IntrusionSet) GetCreatedByRef() string {
	if m != nil {
		return m.CreatedByRef
	}
	return ""
}

func (m *IntrusionSet) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *IntrusionSet) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

func (m *IntrusionSet) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *IntrusionSet) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *IntrusionSet) GetExternalReferences() []*ExternalReference {
	if m != nil {
		return m.ExternalReferences
	}
	return nil
}

func (m *IntrusionSet) GetObjectMarkingRefs() []string {
	if m != nil {
		return m.ObjectMarkingRefs
	}
	return nil
}

func (m *IntrusionSet) GetGranularMarkings() []string {
	if m != nil {
		return m.GranularMarkings
	}
	return nil
}

func (m *IntrusionSet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IntrusionSet) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *IntrusionSet) GetAliases() []string {
	if m != nil {
		return m.Aliases
	}
	return nil
}

func (m *IntrusionSet) GetFirstSeen() string {
	if m != nil {
		return m.FirstSeen
	}
	return ""
}

func (m *IntrusionSet) GetLastSeen() string {
	if m != nil {
		return m.LastSeen
	}
	return ""
}

func (m *IntrusionSet) GetGoals() []string {
	if m != nil {
		return m.Goals
	}
	return nil
}

func (m *IntrusionSet) GetResourceLevel() string {
	if m != nil {
		return m.ResourceLevel
	}
	return ""
}

func (m *IntrusionSet) GetPrimaryMotivation() string {
	if m != nil {
		return m.PrimaryMotivation
	}
	return ""
}

func (m *IntrusionSet) GetSecondaryMotivations() []string {
	if m != nil {
		return m.SecondaryMotivations
	}
	return nil
}

// A type of TTP, also known as malicious code and malicious software,
// used to compromise the confidentiality, integrity, or availability
// of a victim’s data or system.
type Malware struct {
	Type               string               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                 string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedByRef       string               `protobuf:"bytes,3,opt,name=created_by_ref,json=createdByRef,proto3" json:"created_by_ref,omitempty"`
	Created            string               `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Modified           string               `protobuf:"bytes,5,opt,name=modified,proto3" json:"modified,omitempty"`
	Revoked            bool                 `protobuf:"varint,6,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Labels             []string             `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty"`
	ExternalReferences []*ExternalReference `protobuf:"bytes,8,rep,name=external_references,json=externalReferences" json:"external_references,omitempty"`
	ObjectMarkingRefs  []string             `protobuf:"bytes,9,rep,name=object_marking_refs,json=objectMarkingRefs" json:"object_marking_refs,omitempty"`
	GranularMarkings   []string             `protobuf:"bytes,10,rep,name=granular_markings,json=granularMarkings" json:"granular_markings,omitempty"`
	Name               string               `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	Description        string               `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	KillChainPhases    []*KillChainPhase    `protobuf:"bytes,13,rep,name=kill_chain_phases,json=killChainPhases" json:"kill_chain_phases,omitempty"`
	XMitreVersion      string               `protobuf:"bytes,14,opt,name=x_mitre_version,json=xMitreVersion,proto3" json:"x_mitre_version,omitempty"`
	XMitrAliases       []string             `protobuf:"bytes,15,rep,name=x_mitr_aliases,json=xMitrAliases" json:"x_mitr_aliases,omitempty"`
	XMitrePlatforms    []string             `protobuf:"bytes,16,rep,name=x_mitre_platforms,json=xMitrePlatforms" json:"x_mitre_platforms,omitempty"`
	XMitreContributors []string             `protobuf:"bytes,17,rep,name=x_mitre_contributors,json=xMitreContributors" json:"x_mitre_contributors,omitempty"`
}

func (m *Malware) Reset()                    { *m = Malware{} }
func (m *Malware) String() string            { return proto.CompactTextString(m) }
func (*Malware) ProtoMessage()               {}
func (*Malware) Descriptor() ([]byte, []int) { return fileDescriptorStix, []int{10} }

func (m *Malware) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Malware) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Malware) GetCreatedByRef() string {
	if m != nil {
		return m.CreatedByRef
	}
	return ""
}

func (m *Malware) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Malware) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

func (m *Malware) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *Malware) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Malware) GetExternalReferences() []*ExternalReference {
	if m != nil {
		return m.ExternalReferences
	}
	return nil
}

func (m *Malware) GetObjectMarkingRefs() []string {
	if m != nil {
		return m.ObjectMarkingRefs
	}
	return nil
}

func (m *Malware) GetGranularMarkings() []string {
	if m != nil {
		return m.GranularMarkings
	}
	return nil
}

func (m *Malware) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Malware) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Malware) GetKillChainPhases() []*KillChainPhase {
	if m != nil {
		return m.KillChainPhases
	}
	return nil
}

func (m *Malware) GetXMitreVersion() string {
	if m != nil {
		return m.XMitreVersion
	}
	return ""
}

func (m *Malware) GetXMitrAliases() []string {
	if m != nil {
		return m.XMitrAliases
	}
	return nil
}

func (m *Malware) GetXMitrePlatforms() []string {
	if m != nil {
		return m.XMitrePlatforms
	}
	return nil
}

func (m *Malware) GetXMitreContributors() []string {
	if m != nil {
		return m.XMitreContributors
	}
	return nil
}

// Conveys information observed on a system or network (e.g., an IP address).
type ObservedData struct {
	Type               string                      `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                 string                      `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedByRef       string                      `protobuf:"bytes,3,opt,name=created_by_ref,json=createdByRef,proto3" json:"created_by_ref,omitempty"`
	Created            string                      `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Modified           string                      `protobuf:"bytes,5,opt,name=modified,proto3" json:"modified,omitempty"`
	Revoked            bool                        `protobuf:"varint,6,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Labels             []string                    `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty"`
	ExternalReferences []*ExternalReference        `protobuf:"bytes,8,rep,name=external_references,json=externalReferences" json:"external_references,omitempty"`
	ObjectMarkingRefs  []string                    `protobuf:"bytes,9,rep,name=object_marking_refs,json=objectMarkingRefs" json:"object_marking_refs,omitempty"`
	GranularMarkings   []string                    `protobuf:"bytes,10,rep,name=granular_markings,json=granularMarkings" json:"granular_markings,omitempty"`
	FirstObserved      string                      `protobuf:"bytes,11,opt,name=first_observed,json=firstObserved,proto3" json:"first_observed,omitempty"`
	LastObserved       string                      `protobuf:"bytes,12,opt,name=last_observed,json=lastObserved,proto3" json:"last_observed,omitempty"`
	NumberObserved     int64                       `protobuf:"zigzag64,13,opt,name=number_observed,json=numberObserved,proto3" json:"number_observed,omitempty"`
	Objects            map[int64]*ObservableObject `protobuf:"bytes,14,rep,name=objects" json:"objects,omitempty" protobuf_key:"zigzag64,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ObservedData) Reset()                    { *m = ObservedData{} }
func (m *ObservedData) String() string            { return proto.CompactTextString(m) }
func (*ObservedData) ProtoMessage()               {}
func (*ObservedData) Descriptor() ([]byte, []int) { return fileDescriptorStix, []int{11} }

func (m *ObservedData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ObservedData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ObservedData) GetCreatedByRef() string {
	if m != nil {
		return m.CreatedByRef
	}
	return ""
}

func (m *ObservedData) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *ObservedData) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

func (m *ObservedData) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *ObservedData) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ObservedData) GetExternalReferences() []*ExternalReference {
	if m != nil {
		return m.ExternalReferences
	}
	return nil
}

func (m *ObservedData) GetObjectMarkingRefs() []string {
	if m != nil {
		return m.ObjectMarkingRefs
	}
	return nil
}

func (m *ObservedData) GetGranularMarkings() []string {
	if m != nil {
		return m.GranularMarkings
	}
	return nil
}

func (m *ObservedData) GetFirstObserved() string {
	if m != nil {
		return m.FirstObserved
	}
	return ""
}

func (m *ObservedData) GetLastObserved() string {
	if m != nil {
		return m.LastObserved
	}
	return ""
}

func (m *ObservedData) GetNumberObserved() int64 {
	if m != nil {
		return m.NumberObserved
	}
	return 0
}

func (m *ObservedData) GetObjects() map[int64]*ObservableObject {
	if m != nil {
		return m.Objects
	}
	return nil
}

// Collections of threat intelligence focused on one or more topics, such as
// a description of a threat actor, malware, or attack technique, including
// contextual details.
type Report struct {
	Type               string               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                 string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedByRef       string               `protobuf:"bytes,3,opt,name=created_by_ref,json=createdByRef,proto3" json:"created_by_ref,omitempty"`
	Created            string               `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Modified           string               `protobuf:"bytes,5,opt,name=modified,proto3" json:"modified,omitempty"`
	Revoked            bool                 `protobuf:"varint,6,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Labels             []string             `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty"`
	ExternalReferences []*ExternalReference `protobuf:"bytes,8,rep,name=external_references,json=externalReferences" json:"external_references,omitempty"`
	ObjectMarkingRefs  []string             `protobuf:"bytes,9,rep,name=object_marking_refs,json=objectMarkingRefs" json:"object_marking_refs,omitempty"`
	GranularMarkings   []string             `protobuf:"bytes,10,rep,name=granular_markings,json=granularMarkings" json:"granular_markings,omitempty"`
	Name               string               `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	Description        string               `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	Published          string               `protobuf:"bytes,13,opt,name=published,proto3" json:"published,omitempty"`
	ObjectRefs         []string             `protobuf:"bytes,14,rep,name=object_refs,json=objectRefs" json:"object_refs,omitempty"`
}

func (m *Report) Reset()                    { *m = Report{} }
func (m *Report) String() string            { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()               {}
func (*Report) Descriptor() ([]byte, []int) { return fileDescriptorStix, []int{12} }

func (m *Report) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Report) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Report) GetCreatedByRef() string {
	if m != nil {
		return m.CreatedByRef
	}
	return ""
}

func (m *Report) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Report) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

func (m *Report) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *Report) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Report) GetExternalReferences() []*ExternalReference {
	if m != nil {
		return m.ExternalReferences
	}
	return nil
}

func (m *Report) GetObjectMarkingRefs() []string {
	if m != nil {
		return m.ObjectMarkingRefs
	}
	return nil
}

func (m *Report) GetGranularMarkings() []string {
	if m != nil {
		return m.GranularMarkings
	}
	return nil
}

func (m *Report) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Report) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Report) GetPublished() string {
	if m != nil {
		return m.Published
	}
	return ""
}

func (m *Report) GetObjectRefs() []string {
	if m != nil {
		return m.ObjectRefs
	}
	return nil
}

// Individuals, groups, or organizations believed to be operating with
// malicious intent.
type ThreatActor struct {
	Type                 string               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedByRef         string               `protobuf:"bytes,3,opt,name=created_by_ref,json=createdByRef,proto3" json:"created_by_ref,omitempty"`
	Created              string               `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Modified             string               `protobuf:"bytes,5,opt,name=modified,proto3" json:"modified,omitempty"`
	Revoked              bool                 `protobuf:"varint,6,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Labels               []string             `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty"`
	ExternalReferences   []*ExternalReference `protobuf:"bytes,8,rep,name=external_references,json=externalReferences" json:"external_references,omitempty"`
	ObjectMarkingRefs    []string             `protobuf:"bytes,9,rep,name=object_marking_refs,json=objectMarkingRefs" json:"object_marking_refs,omitempty"`
	GranularMarkings     []string             `protobuf:"bytes,10,rep,name=granular_markings,json=granularMarkings" json:"granular_markings,omitempty"`
	Name                 string               `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	Description          string               `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	Aliases              []string             `protobuf:"bytes,13,rep,name=aliases" json:"aliases,omitempty"`
	Roles                []string             `protobuf:"bytes,14,rep,name=roles" json:"roles,omitempty"`
	Goals                []string             `protobuf:"bytes,15,rep,name=goals" json:"goals,omitempty"`
	Sophistication       string               `protobuf:"bytes,16,opt,name=sophistication,proto3" json:"sophistication,omitempty"`
	ResourceLevel        string               `protobuf:"bytes,17,opt,name=resource_level,json=resourceLevel,proto3" json:"resource_level,omitempty"`
	PrimaryMotivation    string               `protobuf:"bytes,18,opt,name=primary_motivation,json=primaryMotivation,proto3" json:"primary_motivation,omitempty"`
	SecondaryMotivations []string             `protobuf:"bytes,19,rep,name=secondary_motivations,json=secondaryMotivations" json:"secondary_motivations,omitempty"`
	PersonalMotivations  []string             `protobuf:"bytes,20,rep,name=personal_motivations,json=personalMotivations" json:"personal_motivations,omitempty"`
}

func (m *ThreatActor) Reset()                    { *m = ThreatActor{} }
func (m *ThreatActor) String() string            { return proto.CompactTextString(m) }
func (*ThreatActor) ProtoMessage()               {}
func (*ThreatActor) Descriptor() ([]byte, []int) { return fileDescriptorStix, []int{13} }

func (m *ThreatActor) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ThreatActor) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ThreatActor) GetCreatedByRef() string {
	if m != nil {
		return m.CreatedByRef
	}
	return ""
}

func (m *ThreatActor) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *ThreatActor) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

func (m *ThreatActor) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *ThreatActor) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ThreatActor) GetExternalReferences() []*ExternalReference {
	if m != nil {
		return m.ExternalReferences
	}
	return nil
}

func (m *ThreatActor) GetObjectMarkingRefs() []string {
	if m != nil {
		return m.ObjectMarkingRefs
	}
	return nil
}

func (m *ThreatActor) GetGranularMarkings() []string {
	if m != nil {
		return m.GranularMarkings
	}
	return nil
}

func (m *ThreatActor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ThreatActor) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ThreatActor) GetAliases() []string {
	if m != nil {
		return m.Aliases
	}
	return nil
}

func (m *ThreatActor) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *ThreatActor) GetGoals() []string {
	if m != nil {
		return m.Goals
	}
	return nil
}

func (m *ThreatActor) GetSophistication() string {
	if m != nil {
		return m.Sophistication
	}
	return ""
}

func (m *ThreatActor) GetResourceLevel() string {
	if m != nil {
		return m.ResourceLevel
	}
	return ""
}

func (m *ThreatActor) GetPrimaryMotivation() string {
	if m != nil {
		return m.PrimaryMotivation
	}
	return ""
}

func (m *ThreatActor) GetSecondaryMotivations() []string {
	if m != nil {
		return m.SecondaryMotivations
	}
	return nil
}

func (m *ThreatActor) GetPersonalMotivations() []string {
	if m != nil {
		return m.PersonalMotivations
	}
	return nil
}

// Legitimate software that can be used by threat actors to perform attacks.
type Tool struct {
	Type               string               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                 string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedByRef       string               `protobuf:"bytes,3,opt,name=created_by_ref,json=createdByRef,proto3" json:"created_by_ref,omitempty"`
	Created            string               `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Modified           string               `protobuf:"bytes,5,opt,name=modified,proto3" json:"modified,omitempty"`
	Revoked            bool                 `protobuf:"varint,6,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Labels             []string             `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty"`
	ExternalReferences []*ExternalReference `protobuf:"bytes,8,rep,name=external_references,json=externalReferences" json:"external_references,omitempty"`
	ObjectMarkingRefs  []string             `protobuf:"bytes,9,rep,name=object_marking_refs,json=objectMarkingRefs" json:"object_marking_refs,omitempty"`
	GranularMarkings   []string             `protobuf:"bytes,10,rep,name=granular_markings,json=granularMarkings" json:"granular_markings,omitempty"`
	Name               string               `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	Description        string               `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	KillChainPhases    []*KillChainPhase    `protobuf:"bytes,13,rep,name=kill_chain_phases,json=killChainPhases" json:"kill_chain_phases,omitempty"`
	ToolVersion        string               `protobuf:"bytes,14,opt,name=tool_version,json=toolVersion,proto3" json:"tool_version,omitempty"`
	XMitreVersion      string               `protobuf:"bytes,15,opt,name=x_mitre_version,json=xMitreVersion,proto3" json:"x_mitre_version,omitempty"`
	XMitrePlatform     []string             `protobuf:"bytes,16,rep,name=x_mitre_platform,json=xMitrePlatform" json:"x_mitre_platform,omitempty"`
	XMitreAliases      []string             `protobuf:"bytes,17,rep,name=x_mitre_aliases,json=xMitreAliases" json:"x_mitre_aliases,omitempty"`
}

func (m *Tool) Reset()                    { *m = Tool{} }
func (m *Tool) String() string            { return proto.CompactTextString(m) }
func (*Tool) ProtoMessage()               {}
func (*Tool) Descriptor() ([]byte, []int) { return fileDescriptorStix, []int{14} }

func (m *Tool) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Tool) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Tool) GetCreatedByRef() string {
	if m != nil {
		return m.CreatedByRef
	}
	return ""
}

func (m *Tool) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Tool) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

func (m *Tool) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *Tool) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Tool) GetExternalReferences() []*ExternalReference {
	if m != nil {
		return m.ExternalReferences
	}
	return nil
}

func (m *Tool) GetObjectMarkingRefs() []string {
	if m != nil {
		return m.ObjectMarkingRefs
	}
	return nil
}

func (m *Tool) GetGranularMarkings() []string {
	if m != nil {
		return m.GranularMarkings
	}
	return nil
}

func (m *Tool) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tool) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Tool) GetKillChainPhases() []*KillChainPhase {
	if m != nil {
		return m.KillChainPhases
	}
	return nil
}

func (m *Tool) GetToolVersion() string {
	if m != nil {
		return m.ToolVersion
	}
	return ""
}

func (m *Tool) GetXMitreVersion() string {
	if m != nil {
		return m.XMitreVersion
	}
	return ""
}

func (m *Tool) GetXMitrePlatform() []string {
	if m != nil {
		return m.XMitrePlatform
	}
	return nil
}

func (m *Tool) GetXMitreAliases() []string {
	if m != nil {
		return m.XMitreAliases
	}
	return nil
}

// A mistake in software that can be directly used by a hacker to gain
// access to a system or network.
type Vulnerability struct {
	Type               string               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                 string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedByRef       string               `protobuf:"bytes,3,opt,name=created_by_ref,json=createdByRef,proto3" json:"created_by_ref,omitempty"`
	Created            string               `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Modified           string               `protobuf:"bytes,5,opt,name=modified,proto3" json:"modified,omitempty"`
	Revoked            bool                 `protobuf:"varint,6,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Labels             []string             `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty"`
	ExternalReferences []*ExternalReference `protobuf:"bytes,8,rep,name=external_references,json=externalReferences" json:"external_references,omitempty"`
	ObjectMarkingRefs  []string             `protobuf:"bytes,9,rep,name=object_marking_refs,json=objectMarkingRefs" json:"object_marking_refs,omitempty"`
	GranularMarkings   []string             `protobuf:"bytes,10,rep,name=granular_markings,json=granularMarkings" json:"granular_markings,omitempty"`
	Name               string               `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	Description        string               `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *Vulnerability) Reset()                    { *m = Vulnerability{} }
func (m *Vulnerability) String() string            { return proto.CompactTextString(m) }
func (*Vulnerability) ProtoMessage()               {}
func (*Vulnerability) Descriptor() ([]byte, []int) { return fileDescriptorStix, []int{15} }

func (m *Vulnerability) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Vulnerability) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vulnerability) GetCreatedByRef() string {
	if m != nil {
		return m.CreatedByRef
	}
	return ""
}

func (m *Vulnerability) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Vulnerability) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

func (m *Vulnerability) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *Vulnerability) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Vulnerability) GetExternalReferences() []*ExternalReference {
	if m != nil {
		return m.ExternalReferences
	}
	return nil
}

func (m *Vulnerability) GetObjectMarkingRefs() []string {
	if m != nil {
		return m.ObjectMarkingRefs
	}
	return nil
}

func (m *Vulnerability) GetGranularMarkings() []string {
	if m != nil {
		return m.GranularMarkings
	}
	return nil
}

func (m *Vulnerability) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vulnerability) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// Used to link two SDOs and to describe how they are related to each other.
type RelationShip struct {
	Type               string               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                 string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedByRef       string               `protobuf:"bytes,3,opt,name=created_by_ref,json=createdByRef,proto3" json:"created_by_ref,omitempty"`
	Created            string               `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Modified           string               `protobuf:"bytes,5,opt,name=modified,proto3" json:"modified,omitempty"`
	Revoked            bool                 `protobuf:"varint,6,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Labels             []string             `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty"`
	ExternalReferences []*ExternalReference `protobuf:"bytes,8,rep,name=external_references,json=externalReferences" json:"external_references,omitempty"`
	ObjectMarkingRefs  []string             `protobuf:"bytes,9,rep,name=object_marking_refs,json=objectMarkingRefs" json:"object_marking_refs,omitempty"`
	GranularMarkings   []string             `protobuf:"bytes,10,rep,name=granular_markings,json=granularMarkings" json:"granular_markings,omitempty"`
	RelationshipType   string               `protobuf:"bytes,11,opt,name=relationship_type,json=relationshipType,proto3" json:"relationship_type,omitempty"`
	Description        string               `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	SourceRef          string               `protobuf:"bytes,13,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	TargetRef          string               `protobuf:"bytes,14,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`
}

func (m *RelationShip) Reset()                    { *m = RelationShip{} }
func (m *RelationShip) String() string            { return proto.CompactTextString(m) }
func (*RelationShip) ProtoMessage()               {}
func (*RelationShip) Descriptor() ([]byte, []int) { return fileDescriptorStix, []int{16} }

func (m *RelationShip) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RelationShip) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RelationShip) GetCreatedByRef() string {
	if m != nil {
		return m.CreatedByRef
	}
	return ""
}

func (m *RelationShip) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *RelationShip) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

func (m *RelationShip) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *RelationShip) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *RelationShip) GetExternalReferences() []*ExternalReference {
	if m != nil {
		return m.ExternalReferences
	}
	return nil
}

func (m *RelationShip) GetObjectMarkingRefs() []string {
	if m != nil {
		return m.ObjectMarkingRefs
	}
	return nil
}

func (m *RelationShip) GetGranularMarkings() []string {
	if m != nil {
		return m.GranularMarkings
	}
	return nil
}

func (m *RelationShip) GetRelationshipType() string {
	if m != nil {
		return m.RelationshipType
	}
	return ""
}

func (m *RelationShip) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RelationShip) GetSourceRef() string {
	if m != nil {
		return m.SourceRef
	}
	return ""
}

func (m *RelationShip) GetTargetRef() string {
	if m != nil {
		return m.TargetRef
	}
	return ""
}

// Denotes the belief that an element of CTI was seen (e.g., indicator, malware).
type Sighting struct {
	Type               string               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                 string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedByRef       string               `protobuf:"bytes,3,opt,name=created_by_ref,json=createdByRef,proto3" json:"created_by_ref,omitempty"`
	Created            string               `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Modified           string               `protobuf:"bytes,5,opt,name=modified,proto3" json:"modified,omitempty"`
	Revoked            bool                 `protobuf:"varint,6,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Labels             []string             `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty"`
	ExternalReferences []*ExternalReference `protobuf:"bytes,8,rep,name=external_references,json=externalReferences" json:"external_references,omitempty"`
	ObjectMarkingRefs  []string             `protobuf:"bytes,9,rep,name=object_marking_refs,json=objectMarkingRefs" json:"object_marking_refs,omitempty"`
	GranularMarkings   []string             `protobuf:"bytes,10,rep,name=granular_markings,json=granularMarkings" json:"granular_markings,omitempty"`
	FirstSeen          string               `protobuf:"bytes,11,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen           string               `protobuf:"bytes,12,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Count              int64                `protobuf:"zigzag64,13,opt,name=count,proto3" json:"count,omitempty"`
	SightingOfRef      []string             `protobuf:"bytes,14,rep,name=sighting_of_ref,json=sightingOfRef" json:"sighting_of_ref,omitempty"`
	ObservedDataRefs   []string             `protobuf:"bytes,15,rep,name=observed_data_refs,json=observedDataRefs" json:"observed_data_refs,omitempty"`
	WhereSightedRefs   []string             `protobuf:"bytes,16,rep,name=where_sighted_refs,json=whereSightedRefs" json:"where_sighted_refs,omitempty"`
	Summary            bool                 `protobuf:"varint,17,opt,name=summary,proto3" json:"summary,omitempty"`
}

func (m *Sighting) Reset()                    { *m = Sighting{} }
func (m *Sighting) String() string            { return proto.CompactTextString(m) }
func (*Sighting) ProtoMessage()               {}
func (*Sighting) Descriptor() ([]byte, []int) { return fileDescriptorStix, []int{17} }

func (m *Sighting) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Sighting) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Sighting) GetCreatedByRef() string {
	if m != nil {
		return m.CreatedByRef
	}
	return ""
}

func (m *Sighting) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Sighting) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

func (m *Sighting) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *Sighting) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Sighting) GetExternalReferences() []*ExternalReference {
	if m != nil {
		return m.ExternalReferences
	}
	return nil
}

func (m *Sighting) GetObjectMarkingRefs() []string {
	if m != nil {
		return m.ObjectMarkingRefs
	}
	return nil
}

func (m *Sighting) GetGranularMarkings() []string {
	if m != nil {
		return m.GranularMarkings
	}
	return nil
}

func (m *Sighting) GetFirstSeen() string {
	if m != nil {
		return m.FirstSeen
	}
	return ""
}

func (m *Sighting) GetLastSeen() string {
	if m != nil {
		return m.LastSeen
	}
	return ""
}

func (m *Sighting) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Sighting) GetSightingOfRef() []string {
	if m != nil {
		return m.SightingOfRef
	}
	return nil
}

func (m *Sighting) GetObservedDataRefs() []string {
	if m != nil {
		return m.ObservedDataRefs
	}
	return nil
}

func (m *Sighting) GetWhereSightedRefs() []string {
	if m != nil {
		return m.WhereSightedRefs
	}
	return nil
}

func (m *Sighting) GetSummary() bool {
	if m != nil {
		return m.Summary
	}
	return false
}

func init() {
	proto.RegisterType((*ExternalReference)(nil), "mitre.stix.v2.ExternalReference")
	proto.RegisterType((*KillChainPhase)(nil), "mitre.stix.v2.KillChainPhase")
	proto.RegisterType((*MarkingDefinition)(nil), "mitre.stix.v2.MarkingDefinition")
	proto.RegisterType((*ObservableObject)(nil), "mitre.stix.v2.ObservableObject")
	proto.RegisterType((*AttackPattern)(nil), "mitre.stix.v2.AttackPattern")
	proto.RegisterType((*Campaign)(nil), "mitre.stix.v2.Campaign")
	proto.RegisterType((*CourseOfAction)(nil), "mitre.stix.v2.CourseOfAction")
	proto.RegisterType((*Identity)(nil), "mitre.stix.v2.Identity")
	proto.RegisterType((*Indicator)(nil), "mitre.stix.v2.Indicator")
	proto.RegisterType((*IntrusionSet)(nil), "mitre.stix.v2.IntrusionSet")
	proto.RegisterType((*Malware)(nil), "mitre.stix.v2.Malware")
	proto.RegisterType((*ObservedData)(nil), "mitre.stix.v2.ObservedData")
	proto.RegisterType((*Report)(nil), "mitre.stix.v2.Report")
	proto.RegisterType((*ThreatActor)(nil), "mitre.stix.v2.ThreatActor")
	proto.RegisterType((*Tool)(nil), "mitre.stix.v2.Tool")
	proto.RegisterType((*Vulnerability)(nil), "mitre.stix.v2.Vulnerability")
	proto.RegisterType((*RelationShip)(nil), "mitre.stix.v2.RelationShip")
	proto.RegisterType((*Sighting)(nil), "mitre.stix.v2.Sighting")
}

func init() { proto.RegisterFile("pkg/protocol/mitre/stix/v2/stix.proto", fileDescriptorStix) }

var fileDescriptorStix = []byte{
	// 1613 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x5a, 0xdd, 0x6f, 0x5b, 0x49,
	0x15, 0x57, 0xe2, 0x38, 0x8e, 0x8f, 0xbf, 0x27, 0x29, 0xba, 0xa4, 0x8d, 0x1a, 0x4c, 0x3f, 0x22,
	0x5a, 0x1c, 0xea, 0x0a, 0x09, 0x21, 0x01, 0x4a, 0xd2, 0x22, 0x45, 0x10, 0x12, 0xae, 0x4b, 0x8a,
	0xa0, 0xd2, 0xd5, 0xf8, 0xde, 0xb1, 0x3d, 0xf8, 0xde, 0x3b, 0x66, 0x66, 0xec, 0xc6, 0xfc, 0x01,
	0xfd, 0x0b, 0x10, 0xea, 0x0b, 0x2f, 0xbc, 0x80, 0xf8, 0x4b, 0x10, 0x6f, 0x7d, 0x47, 0xe2, 0x2f,
	0x59, 0x69, 0x35, 0x5f, 0xf6, 0xb5, 0x9b, 0xee, 0x6a, 0x57, 0xaa, 0x36, 0xbb, 0xeb, 0xa7, 0xdc,
	0xf3, 0x3b, 0xe7, 0xcc, 0xc7, 0xf9, 0x98, 0x39, 0x73, 0x1c, 0xb8, 0x3f, 0x1a, 0xf6, 0x0f, 0x47,
	0x9c, 0x49, 0x16, 0xb2, 0xf8, 0x30, 0xa1, 0x92, 0x93, 0x43, 0x21, 0xe9, 0xd5, 0xe1, 0xa4, 0xad,
	0xff, 0xb6, 0x34, 0x0f, 0x55, 0x34, 0xa7, 0xa5, 0x91, 0x49, 0xbb, 0xd9, 0x87, 0xc6, 0xf3, 0x2b,
	0x49, 0x78, 0x8a, 0x63, 0x9f, 0xf4, 0x08, 0x27, 0x69, 0x48, 0xd0, 0x5d, 0x28, 0x09, 0x36, 0xe6,
	0x21, 0x09, 0x52, 0x9c, 0x10, 0x6f, 0x6d, 0x7f, 0xed, 0xa0, 0xe8, 0x83, 0x81, 0x7e, 0x83, 0x13,
	0x2d, 0x40, 0xac, 0x56, 0x40, 0x23, 0x6f, 0xdd, 0x08, 0x38, 0xe8, 0x34, 0x42, 0x75, 0xc8, 0x8d,
	0x79, 0xec, 0xe5, 0x34, 0x43, 0x7d, 0x36, 0x5f, 0x42, 0xf5, 0x57, 0x34, 0x8e, 0x4f, 0x06, 0x98,
	0xa6, 0x17, 0x03, 0x2c, 0x08, 0xda, 0x03, 0x18, 0xa9, 0x8f, 0xec, 0x24, 0x45, 0x8d, 0xe8, 0x39,
	0x1e, 0x40, 0x6d, 0x48, 0xe3, 0x38, 0x08, 0x95, 0x86, 0x91, 0x31, 0xf3, 0x54, 0x86, 0x6e, 0x1c,
	0x25, 0xd7, 0x7c, 0xb7, 0x0e, 0x8d, 0x33, 0xcc, 0x87, 0x34, 0xed, 0x3f, 0x23, 0x3d, 0x9a, 0x52,
	0x49, 0x59, 0x8a, 0x10, 0x6c, 0xc8, 0xe9, 0xc8, 0x0d, 0xab, 0xbf, 0x51, 0x15, 0xd6, 0x67, 0x8b,
	0x5d, 0xa7, 0x11, 0xba, 0x07, 0xd5, 0x90, 0x13, 0x2c, 0x49, 0x14, 0x74, 0xa7, 0x01, 0x27, 0x3d,
	0xbb, 0xde, 0xb2, 0x45, 0x8f, 0xa7, 0x3e, 0xe9, 0x21, 0x0f, 0x0a, 0x96, 0xf6, 0x36, 0x34, 0xdb,
	0x91, 0x68, 0x17, 0xb6, 0x12, 0x16, 0xd1, 0x1e, 0x25, 0x91, 0x97, 0xd7, 0xac, 0x19, 0x8d, 0x1e,
	0x42, 0x2d, 0x9a, 0xad, 0x26, 0xd0, 0x4b, 0x29, 0x6a, 0x91, 0xea, 0x1c, 0x7e, 0xa1, 0x16, 0xd5,
	0x81, 0xd2, 0x1c, 0x11, 0x1e, 0xec, 0xe7, 0x0e, 0x4a, 0xed, 0x27, 0xad, 0x05, 0x2f, 0xb5, 0xde,
	0xdb, 0x5f, 0x6b, 0xfe, 0x29, 0x9e, 0xa7, 0x92, 0x4f, 0xfd, 0xec, 0x28, 0xbb, 0x3f, 0x87, 0xfa,
	0xb2, 0x80, 0x72, 0xc9, 0x90, 0x4c, 0xad, 0x41, 0xd4, 0x27, 0xda, 0x81, 0xfc, 0x04, 0xc7, 0x63,
	0x67, 0x57, 0x43, 0xfc, 0x74, 0xfd, 0x27, 0x6b, 0xcd, 0x07, 0x50, 0x3f, 0xef, 0x0a, 0xc2, 0x27,
	0xb8, 0x1b, 0x93, 0xf3, 0xee, 0x9f, 0x48, 0x28, 0xaf, 0xb3, 0x68, 0xf3, 0x6d, 0x01, 0x2a, 0x47,
	0x52, 0xe2, 0x70, 0x78, 0x81, 0xa5, 0x72, 0xfe, 0x57, 0x6e, 0x77, 0x0f, 0x0a, 0x9c, 0x4c, 0xd8,
	0x90, 0x44, 0xde, 0xe6, 0xfe, 0xda, 0xc1, 0x96, 0xef, 0x48, 0xf4, 0x1d, 0xd8, 0x8c, 0x71, 0x97,
	0xc4, 0xc2, 0x2b, 0xec, 0xe7, 0x0e, 0x8a, 0xbe, 0xa5, 0xd0, 0x6f, 0x61, 0x7b, 0x16, 0xcb, 0xdc,
	0xa5, 0x80, 0xf0, 0xb6, 0xb4, 0x23, 0xf6, 0x97, 0x1c, 0xf1, 0x5e, 0xae, 0xf8, 0x88, 0x2c, 0x43,
	0x02, 0xb5, 0x60, 0x9b, 0x69, 0xa3, 0x05, 0x89, 0x71, 0x9c, 0x1a, 0x58, 0x78, 0x45, 0x3d, 0x6f,
	0xc3, 0xb0, 0xac, 0x4b, 0x7d, 0xd2, 0x13, 0xe8, 0x11, 0x34, 0xfa, 0x1c, 0xa7, 0xe3, 0x18, 0x73,
	0xa7, 0x61, 0x22, 0xa1, 0xe8, 0xd7, 0x1d, 0xc3, 0xca, 0x0b, 0x65, 0x61, 0x9d, 0x0c, 0x25, 0x63,
	0x61, 0xf5, 0x8d, 0xf6, 0x55, 0x10, 0x89, 0x90, 0xd3, 0x91, 0x72, 0xb8, 0x57, 0xd6, 0xac, 0x2c,
	0x84, 0x4e, 0xa1, 0x91, 0xc9, 0x26, 0x9d, 0x65, 0xc2, 0xab, 0xe8, 0x3d, 0xee, 0x2d, 0xed, 0x71,
	0x31, 0x4d, 0xfd, 0xda, 0x70, 0x81, 0x16, 0x2a, 0x31, 0xaf, 0x02, 0xad, 0x12, 0x4c, 0x08, 0x17,
	0x6a, 0xc2, 0xaa, 0x49, 0xcc, 0xab, 0x33, 0x85, 0x5e, 0x1a, 0x10, 0xfd, 0x02, 0xee, 0x38, 0xb9,
	0x11, 0xe1, 0x09, 0x15, 0x0a, 0x15, 0x01, 0x27, 0x7f, 0x1e, 0x53, 0x4e, 0x22, 0xaf, 0xa6, 0x37,
	0xf8, 0x5d, 0xa3, 0x74, 0x31, 0x97, 0xf0, 0xad, 0x00, 0xfa, 0x01, 0x34, 0x66, 0x03, 0xc4, 0x58,
	0xf6, 0x18, 0x4f, 0x84, 0x57, 0xd7, 0x5a, 0x35, 0xab, 0xe5, 0xe0, 0xac, 0x6c, 0x44, 0x24, 0x09,
	0xb5, 0x1d, 0x1a, 0x7a, 0x59, 0x56, 0xf6, 0x99, 0x83, 0xd1, 0x8f, 0x60, 0xc7, 0xc9, 0x86, 0x2c,
	0x95, 0x9c, 0x76, 0xc7, 0x92, 0x71, 0xe1, 0x21, 0x3d, 0x34, 0x32, 0xe2, 0x27, 0x19, 0x0e, 0x3a,
	0x9c, 0x6b, 0x44, 0x58, 0xe2, 0xc0, 0x1c, 0x85, 0xc2, 0xdb, 0x36, 0x1e, 0xb5, 0x13, 0x60, 0x89,
	0x3b, 0x86, 0x81, 0x8e, 0x60, 0xcf, 0x29, 0x90, 0x5e, 0x4f, 0xcd, 0x3b, 0x59, 0xb0, 0x82, 0xb7,
	0xa3, 0x35, 0x77, 0x8d, 0xe6, 0x73, 0x27, 0x92, 0xb1, 0x02, 0xfa, 0x19, 0xdc, 0x76, 0x43, 0x88,
	0xa9, 0x90, 0x24, 0x71, 0x96, 0x4b, 0x48, 0x2a, 0x85, 0x77, 0x4b, 0x0f, 0xe0, 0x99, 0x01, 0x3a,
	0x5a, 0xc0, 0xcf, 0xf0, 0x9b, 0x7f, 0xdb, 0x80, 0xad, 0x13, 0x9c, 0x8c, 0x30, 0xed, 0xaf, 0xb2,
	0xf2, 0xa6, 0x66, 0xa5, 0x07, 0x05, 0x1c, 0xd3, 0x59, 0x2e, 0x16, 0x7d, 0x47, 0xaa, 0xcb, 0xb1,
	0x47, 0xb9, 0x90, 0x81, 0x20, 0xc4, 0xe5, 0x57, 0x51, 0x23, 0x1d, 0x42, 0x52, 0x74, 0x1b, 0x8a,
	0x31, 0x76, 0xdc, 0x9a, 0xb1, 0xb6, 0x02, 0x34, 0xf3, 0x0e, 0x14, 0xcd, 0x6e, 0xe8, 0x84, 0x78,
	0x75, 0xa3, 0x3a, 0x03, 0x9a, 0xff, 0xca, 0x41, 0xf5, 0x84, 0x8d, 0xb9, 0x20, 0xe7, 0xbd, 0xa3,
	0xf0, 0x46, 0x5c, 0x96, 0xab, 0xf0, 0xb8, 0x36, 0x3c, 0x9a, 0x7f, 0xdd, 0x80, 0xad, 0xd3, 0x88,
	0xa4, 0x92, 0xca, 0xe9, 0xca, 0x49, 0x37, 0x34, 0x87, 0xef, 0x43, 0x95, 0x5a, 0x1f, 0x05, 0x61,
	0x8c, 0x85, 0x4a, 0x65, 0x7d, 0x1b, 0x3a, 0xf4, 0x44, 0x81, 0xca, 0x7c, 0x82, 0x84, 0xfa, 0x9e,
	0xa9, 0x9a, 0x54, 0xb7, 0x24, 0x3a, 0x84, 0x6d, 0x75, 0x0d, 0xe1, 0x50, 0x06, 0x34, 0x55, 0xb7,
	0x19, 0xd6, 0x53, 0x99, 0xac, 0x46, 0x96, 0x75, 0x3a, 0xe7, 0x34, 0xff, 0xb3, 0x01, 0xc5, 0xd3,
	0x34, 0xa2, 0x21, 0x96, 0x8c, 0xaf, 0xe2, 0xe2, 0xe6, 0x9e, 0xed, 0x23, 0x53, 0x14, 0xdb, 0x80,
	0x70, 0xa4, 0x3a, 0xdb, 0x27, 0x38, 0xa6, 0x51, 0xd0, 0xe3, 0x2c, 0x71, 0x67, 0xbb, 0x46, 0x7e,
	0xc9, 0x59, 0xa2, 0x1e, 0x57, 0x86, 0x3d, 0x4e, 0x25, 0x8d, 0x6d, 0x1c, 0x18, 0x8d, 0xdf, 0x29,
	0xe4, 0xfa, 0x5a, 0xae, 0xfe, 0x65, 0x6a, 0xb9, 0xe6, 0xdf, 0xf3, 0x50, 0x3e, 0x4d, 0x25, 0x1f,
	0xab, 0x9a, 0xa3, 0x43, 0xe4, 0x2a, 0x9a, 0xbe, 0x55, 0x95, 0xc2, 0x0e, 0xe4, 0xfb, 0x0c, 0xc7,
	0xae, 0xaa, 0x36, 0x84, 0x3a, 0xd1, 0x38, 0xb1, 0x0d, 0x80, 0x98, 0x4c, 0x48, 0x6c, 0x0b, 0xe9,
	0x8a, 0x43, 0x7f, 0xad, 0x40, 0xf4, 0x43, 0x40, 0x23, 0x4e, 0x13, 0xcc, 0xa7, 0x41, 0xc2, 0x24,
	0x9d, 0x98, 0x63, 0x0b, 0x69, 0xd1, 0x86, 0xe5, 0x9c, 0xcd, 0x18, 0xe8, 0x29, 0xdc, 0x12, 0x24,
	0x64, 0x69, 0xb4, 0xa8, 0xe0, 0x8a, 0xe8, 0x9d, 0x19, 0x73, 0xae, 0x23, 0x9a, 0x6f, 0xf3, 0x50,
	0x38, 0xc3, 0xf1, 0x6b, 0xcc, 0xc9, 0x2a, 0x34, 0x57, 0x4f, 0x4b, 0xf7, 0xb4, 0xbc, 0x07, 0x55,
	0x23, 0x17, 0xb8, 0xa4, 0x30, 0x8f, 0xc9, 0xb2, 0x16, 0x3b, 0xb2, 0x99, 0xf1, 0x45, 0xde, 0x8f,
	0x1f, 0x7a, 0x13, 0x36, 0x3e, 0xf4, 0x26, 0x6c, 0xbe, 0xc9, 0x43, 0xd9, 0x34, 0x49, 0x48, 0xa4,
	0x9e, 0x7e, 0xab, 0xf8, 0xfc, 0xe8, 0xf1, 0x79, 0x1f, 0xaa, 0xe6, 0xa8, 0x63, 0xd6, 0xee, 0x36,
	0x52, 0x2b, 0x1a, 0x75, 0xce, 0x40, 0xdf, 0x87, 0x8a, 0x3e, 0xf2, 0x66, 0x52, 0x26, 0x68, 0xcb,
	0x0a, 0x9c, 0x09, 0x3d, 0x84, 0x5a, 0x3a, 0x4e, 0xba, 0x84, 0xcf, 0xc5, 0xd4, 0x35, 0x8d, 0xfc,
	0xaa, 0x81, 0x67, 0x82, 0xc7, 0x50, 0x30, 0xcb, 0x36, 0x85, 0x5b, 0xa9, 0x7d, 0xb0, 0x64, 0x98,
	0x6c, 0x10, 0xb4, 0x4c, 0xb3, 0xcc, 0xf6, 0xe4, 0x9c, 0xe2, 0xee, 0x1f, 0x55, 0xa8, 0xcc, 0x19,
	0xd9, 0x5e, 0x1c, 0x32, 0xbd, 0xb8, 0x1f, 0x67, 0x7b, 0x71, 0xa5, 0xf6, 0xdd, 0x6b, 0xe7, 0x98,
	0x77, 0xe3, 0xb2, 0xcd, 0xba, 0xff, 0xe7, 0x60, 0xd3, 0x27, 0x23, 0xc6, 0x57, 0xb7, 0xf7, 0x4d,
	0x3d, 0x22, 0xef, 0x40, 0x71, 0x34, 0xee, 0xc6, 0x54, 0x0c, 0x6c, 0x98, 0x15, 0xfd, 0x39, 0xa0,
	0x0a, 0x3e, 0xbb, 0x60, 0xbd, 0x50, 0xf3, 0x3c, 0x00, 0x03, 0xa9, 0x15, 0x36, 0xdf, 0xe5, 0xa1,
	0xf4, 0x62, 0xa0, 0xec, 0x7f, 0x14, 0xae, 0x4a, 0xfe, 0xaf, 0x63, 0x91, 0xb6, 0x03, 0x79, 0xce,
	0x62, 0xe2, 0x9c, 0x6b, 0x88, 0x79, 0xf9, 0x55, 0xcb, 0x96, 0x5f, 0x0f, 0xa0, 0x2a, 0xd8, 0x68,
	0x40, 0x85, 0x54, 0x2f, 0x3c, 0x35, 0x95, 0xe9, 0xe1, 0x2c, 0xa1, 0x37, 0xa8, 0x4c, 0x43, 0x4f,
	0x60, 0x67, 0x44, 0xb8, 0x60, 0xca, 0xbd, 0x59, 0x1d, 0xd3, 0xe5, 0xdc, 0x76, 0xbc, 0x6c, 0x65,
	0xf7, 0x26, 0x0f, 0x1b, 0x2f, 0x18, 0x8b, 0x57, 0xc1, 0xfc, 0xcd, 0x2f, 0xeb, 0xbe, 0x07, 0x65,
	0xc9, 0x58, 0xbc, 0x54, 0xd3, 0x95, 0x14, 0xe6, 0x2a, 0xba, 0x6b, 0x2a, 0xbf, 0xda, 0x75, 0x95,
	0xdf, 0x01, 0xd4, 0x97, 0x6b, 0x3a, 0x5b, 0xd2, 0x55, 0x17, 0x4b, 0xba, 0xec, 0x88, 0x2e, 0x29,
	0x4d, 0x31, 0x67, 0x47, 0xb4, 0x55, 0x62, 0xf3, 0x9f, 0x39, 0xa8, 0x5c, 0x8e, 0xe3, 0x94, 0x70,
	0xdc, 0xa5, 0xf1, 0xaa, 0xd3, 0x76, 0x73, 0xdb, 0xa1, 0x9f, 0xe4, 0xa0, 0xec, 0x93, 0x58, 0x1f,
	0x20, 0x9d, 0x01, 0x1d, 0xad, 0x1c, 0xf5, 0xd1, 0x1d, 0xf5, 0x08, 0x1a, 0xdc, 0x5a, 0x5c, 0x0c,
	0xe8, 0xc8, 0xfc, 0x90, 0x6d, 0xbc, 0x56, 0xcf, 0x32, 0xf4, 0x4f, 0xd9, 0x9f, 0x7f, 0xa6, 0xec,
	0x81, 0xfd, 0x2f, 0x02, 0xed, 0x08, 0x5b, 0x08, 0x19, 0x44, 0x79, 0x61, 0x0f, 0x40, 0x62, 0xde,
	0x27, 0xba, 0x10, 0x72, 0xad, 0x0c, 0x83, 0xf8, 0xa4, 0xd7, 0xfc, 0xdf, 0x06, 0x6c, 0x75, 0x68,
	0x7f, 0x20, 0x69, 0xda, 0x5f, 0xf9, 0xfe, 0xa3, 0xfb, 0x7e, 0xb1, 0xb1, 0x54, 0xfa, 0xcc, 0xc6,
	0x52, 0xf9, 0xfd, 0xc6, 0x52, 0xc8, 0xc6, 0xa9, 0xb4, 0x6f, 0x2a, 0x43, 0xa8, 0x23, 0x59, 0x58,
	0xff, 0x05, 0xac, 0x67, 0x9d, 0xac, 0x8f, 0x64, 0x07, 0x9f, 0xf7, 0x94, 0x47, 0x1e, 0x03, 0x72,
	0x8f, 0x32, 0xf3, 0x7b, 0xab, 0xde, 0x95, 0x29, 0x92, 0xea, 0x2c, 0xf3, 0xdc, 0xd2, 0x9b, 0x7a,
	0x0c, 0xe8, 0xf5, 0x80, 0x70, 0x12, 0xe8, 0x41, 0x48, 0x64, 0xa4, 0xcd, 0xa5, 0x50, 0xd7, 0x9c,
	0x8e, 0x61, 0x68, 0x69, 0x0f, 0x0a, 0x62, 0x9c, 0xa8, 0xa2, 0x47, 0x97, 0x4b, 0x5b, 0xbe, 0x23,
	0x8f, 0x5f, 0xc2, 0x2e, 0xe3, 0xfd, 0xd6, 0x5f, 0x48, 0x4a, 0xe5, 0x00, 0xf3, 0x45, 0x87, 0x1c,
	0x17, 0x3b, 0x92, 0x5e, 0x5d, 0x70, 0x26, 0xd9, 0xc5, 0xda, 0x1f, 0x36, 0x15, 0x3a, 0x69, 0xff,
	0x63, 0x3d, 0x77, 0xd6, 0xf9, 0xfd, 0xbf, 0xd7, 0x2b, 0xfa, 0x42, 0x69, 0x29, 0x89, 0xd6, 0x65,
	0xfb, 0xbf, 0x96, 0x7e, 0xa5, 0xe8, 0x57, 0x97, 0xed, 0xee, 0xa6, 0xfe, 0xcf, 0x9b, 0xa7, 0x9f,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x56, 0xdd, 0x6a, 0x43, 0xa2, 0x23, 0x00, 0x00,
}
